apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: my-postgres-cluster
  namespace: staging
spec:
  postgresVersion: 16
  instances:
    - name: instance1
      replicas: 5
      dataVolumeClaimSpec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi # Adjust size as per your requirements
  database:
    name: mydatabase
  users:
    - name: myuser
      databases:
        - mydatabase
    - name: extrauser  # New user for the additional database
      databases:
        - extradb
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
