apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: my-postgres-cluster
  namespace: postgres-operator
spec:
  postgresVersion: 15
  instances:
    - name: instance1
      replicas: 3
      dataVolumeClaimSpec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi # Adjust size as per your requirements
  database:
    name: mydatabase
  users:
    - name: myuser
      databases:
        - mydatabase
  patroni:
    dynamicConfiguration:
      synchronous_mode: true

